
title: The Back Room
description: Open-Source Development and Customization
baseurl: ""
url: "https://the-back-room.info"

remote_theme: "just-the-docs/just-the-docs"

color_scheme: dark

social_image: "/assets/images/social-preview.jpg"

favicon_ico: "/favicon.ico"

permalink: pretty

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

search_enabled: true

mermaid:
  version: "9.1.6"

liquid:
  error_mode: strict
  strict_filters: true

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    color: blue
  new:
    color: green
  note:
    color: purple
  warning:
    color: red

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap


kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
