
title: The Back Room
description: Open-Source Development and Customization
baseurl: ""
url: "https://the-back-room.info"

remote_theme: "just-the-docs/just-the-docs"

color_scheme: dracula

social_image: "/assets/images/logo.png"
favicon_ico: "/favicon.ico"

permalink: pretty

search_enabled: true

mermaid:
  version: "9.1.6"

liquid:
  error_mode: strict
  strict_filters: true

callouts_level: quiet
callouts:
  highlight:
    color: f1fa8c # dracula yellow (RGB 241 250 140 )
  important:
    color: 8be9fd # dracula cyan (RGB 139 233 253)
  new:
    color: 50fa7b # dracula green (RGB 80 250 123)
  note:
    color: bd93f9 # dracula purple (RGB 189 147 249)
  warning:
    color: ff5555 # dracula red (RGB 255 85 85)

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [] 
  blanklines: false
  profile: false