
title: The Back Room
description: Open-Source Development and Customization
baseurl: ""
url: "https://the-back-room.info"

remote_theme: "just-the-docs/just-the-docs"

color_scheme: dracula

social_image: "/assets/images/logo.png"
favicon_ico: "/favicon.ico"

permalink: pretty

search_enabled: true

mermaid:
  version: "9.1.6"

liquid:
  error_mode: strict
  strict_filters: true

callouts_level: quiet
callouts:
  highlight:
    color: yellow 
  important:
    color: blue
    title: "ℹ️ Important"
    title_color: white
  new:
    color: green
    title: "🆕 New"
    title_color: white
  note:
    color: purple
    title: "📝 Note"
    title_color: white
  warning:
    color: red
    title: "⚠️ Warning"
    title_color: white

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [] 
  blanklines: false
  profile: false