title: The Back Room
description: Open-Source Development and Customization

permalink: pretty

favicon_ico: "/favicon.ico"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p" 

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-last-modified-at