
title: The Back Room
description: Open-Source Development and Customization
baseurl: ""
url: "https://the-back-room.info"

remote_theme: "just-the-docs/just-the-docs"

color_scheme: dracula

social_image: "/assets/images/logo.png"
favicon_ico: "/favicon.ico"

permalink: pretty

search_enabled: true
search.button: true
search.previews: 3
search.preview_words_after: 10
search.tokenizer_separator: /[\s/]+/
search:
    focus_shortcut_key: 'k'

heading_anchors: true

mermaid:
  version: "9.1.6"

liquid:
  error_mode: strict
  strict_filters: true

callouts_level: quiet
callouts:
  highlight:
    color: yellow-000
    appearance: minimal
  important:
    color: blue-000
    appearance: minimal
    title: Important
  new:
    color: green-000
    appearance: minimal
    title: New
  note:
    color: purple-000
    appearance: minimal
    title: Note
  warning:
    color: red-000
    appearance: minimal
    title: Warning

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [] 
  blanklines: false
  profile: false