
# File: _config.yml
# --- a/file:///c%3A/Users/User/Projects/The-Back-Room.github.io/_config.yml
# +++ b/file:///c%3A/Users/User/Projects/The-Back-Room.github.io/_config.yml
# @@ -1,6 +1,6 @@
# ---
#  title: The Back Room
#  description: Open-Source Development and Customization
#  baseurl: ""
#  url: "https://the-back-room.info"
#  remote_theme: "cotes2020/jekyll-theme-chirpy"
#  theme_mode: dark
#  favicon_ico: "/favicon.ico"
#  social_preview_image: "/assets/images/social-preview.jpg"
#  last_edit_timestamp: true
#  last_edit_time_format: "%b %e %Y at %I:%M %p"
#  last_edit_time_zone: "UTC"
#  last_edit_author: true
#  last_edit_author_format: "%a, %b %e %I:%M %p %Z"
#  defaults:
#    - scope:
#  plugins: 
#    - jekyll-seo-tag
#    - jekyll-github-metadata 
#    - jekyll-include-cache
#    - jekyll-sitemap 
#    - jekyll-feed
#    - jekyll-last-modified-at  
#    - jekyll-redirect-from
#    - jekyll-archives  
#    - jekyll-paginate
# --- IGNORE --- 


title: The Back Room
description: Open-Source Development and Customization
baseurl: ""
url: "https://the-back-room.info"

remote_theme: "cotes2020/jekyll-theme-chirpy"
theme_mode: dark

favicon_ico: "/favicon.ico"

social_preview_image: "/assets/images/social-preview.jpg"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p" 
last_edit_time_zone: "UTC"
last_edit_author: true
last_edit_author_format: "%a, %b %e %I:%M %p %Z"
defaults:
  - scope:

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-paginate
paginate: 10
paginate_path: "/page/:num"
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
    archive:
      type: monthly
      format: "%Y-%m"
      permalink: /archive/:path/
  themes:
    output: true
    permalink: /themes/:name/
  pages:
    output: true
    permalink: /:name/
  snippets:
    output: true
    permalink: /snippets/:name/
  images:
    output: true
    permalink: /images/:name/
  videos:
    output: true
    permalink: /videos/:name/
  audio:
    output: true
    permalink: /audio/:name/
  downloads:
    output: true
    permalink: /downloads/:name/
  links:
    output: true
    permalink: /links/:name/
  projects:
    output: true
    permalink: /projects/:name/
  articles:
    output: true
    permalink: /articles/:name/
  tutorials:
    output: true
    permalink: /tutorials/:name/
  guides:
    output: true
    permalink: /guides/:name/
  news:
    output: true
    permalink: /news/:name/
  announcements:
    output: true
    permalink: /announcements/:name/
  updates:
    output: true
    permalink: /updates/:name/
  changelogs:
    output: true
    permalink: /changelogs/:name/
  releases:
    output: true
    permalink: /releases/:name/
