name: Take screenshot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: https://the-back-room.info
      - uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: ${{ github.workspace }}/.github/assets/*.png
