name: Take screenshot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Webpage Screenshot Action
        uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: https://the-back-room.info
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./screenshot.png
